### ISSUE TITLE
Connection Refused on 32400

### ISSUE THREAD

**Issue by styk-tv** [hoppity/kafka-http-proxy#43]
Startup fails with below error. Not sure where that address/port comes from. Zoo and kafka is up however no topics (maybe that has something to do with that). I'm attaching exception and at the bottom connectivity verification from rest pod.

Any suggestions would be cool.

```[2018-04-25T19:18:19.633Z]  INFO: kafka-http-proxy/279 on kafka-rest-7d467d844b-6wqbw(/usr/local/src/server.js:60): Application listening on port 2181
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 172.174.30.177:32400
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
```

Connectivity is there
```
root@kafka-rest-7d467d844b-6wqbw:/usr/local/src# 
root@kafka-rest-7d467d844b-6wqbw:/usr/local/src# ping pzoo
PING pzoo.kafka.svc.cluster.local (100.96.1.53): 56 data bytes
64 bytes from 100.96.1.53: icmp_seq=0 ttl=64 time=0.075 ms
64 bytes from 100.96.1.53: icmp_seq=1 ttl=64 time=0.106 ms
^C--- pzoo.kafka.svc.cluster.local ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max/stddev = 0.075/0.090/0.106/0.000 ms
root@kafka-rest-7d467d844b-6wqbw:/usr/local/src# 
root@kafka-rest-7d467d844b-6wqbw:/usr/local/src# telnet pzoo 2181
Trying 100.96.1.53...
Connected to pzoo.kafka.svc.cluster.local.
Escape character is '^]'.
^]
telnet> 
```

**Comment by ducas** [comment]
Hi! A little more info on your configuration might be helpful. 32400 is the Plex port (according to google...) so I'm not sure how you're getting that either 😄

**Comment by styk-tv** [comment]
I'm launching your docker container from here https://hub.docker.com/r/hoppity/kafka-http-proxy/ in kubernetes in same namespace as kafka. I have only one kafka node and one zookeeper node but they are working fine and are resolvable. As to the configuration you can see above address is resolvable.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-rest
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-rest
  template:
    metadata:
      labels:
        app: kafka-rest
    spec:
      containers:
      - name: kafka-rest
        image: hoppity/kafka-http-proxy
        ports:
        - containerPort: 8085
        env:
        - name: ZOOKEEPER_CONNECT
          value: pzoo:2181
```

above config is in exports
```
declare -x ZOOKEEPER_CONNECT="pzoo:2181"
```
